services:
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "3030:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@a.mn
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pg-admin-data:/var/lib/pgadmin
    networks:
      - dbnet
  db:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: goscraper
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge

volumes:
  pg-data:
  pg-admin-data: